### ISSUE TITLE
Add a search button to shop search field

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#67] opened 2015-12-02 17:36 UTC
I know this seems silly but I think we have a lot of older customers who use our website to order books, I think they would be more comfortable with an actual button they push. It could just be a little one that says "go" at the end for the search field box.

**Comment by budparr** [comment] 2015-12-03 20:47
This is a duplicate of #58, I believe, so I'm going to close it, but feel free to reopen if that's not right.

**Closed by budparr** 2015-12-03 20:47 UTC
