### ISSUE TITLE
fix stick figure amy mobile view

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#141] opened 2016-03-04 22:36 UTC
so looking at the stick figure amy blog post on my mobile, it's a little wonky.
attached three screen shots -
![image1](https://cloud.githubusercontent.com/assets/15218891/13542284/9269b8d4-e22f-11e5-8809-0c34682f2346.PNG)
![image2](https://cloud.githubusercontent.com/assets/15218891/13542285/9359cd74-e22f-11e5-9f0a-fbd4bc2574fc.PNG)
![image3](https://cloud.githubusercontent.com/assets/15218891/13542286/94a5c818-e22f-11e5-9959-f34c71248301.PNG)

**Comment by budparr** [comment] 2016-03-05 03:23
Can you tell me what browser/system that is? It's not coming up at all on my tests. It looks like the page didn't load entirely, rather than a bug.

**Comment by shuchibooksmith** [comment] 2016-03-05 16:01
safari, via iphone. 
  
    Shuchi Saraswat
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

 P Please consider the environment before printing this email.   

   

  

----------------------------------------

**Comment by budparr** [comment] 2016-03-05 18:48
Can you tell me which iPhone and OS? I can't replicate this issue in any
tests.

**Comment by shuchibooksmith** [comment] 2016-03-07 15:13
i have an iphone 5s
os 9.2.1

amy has the same issue on her device too, she's sending me the info

**Comment by budparr** [comment] 2016-03-07 15:16
Okay, that's helpful. I'll do some testing on that exact setup.

**Comment by budparr** [comment] 2016-03-07 15:20
Do you see that sort of behavior elsewhere at all? At the least, other pages? Still coming up normal for me on test units.

**Comment by budparr** [comment] 2016-03-07 15:26
I took off some "value added" stuff the DISQUS commenting system was adding to the page. My only guess at this point is that the third-party script for the comments was blocking the loading of the page. At any rate, that's what it looks like, and could be why it's not happening on my test devices. Can you wait 5 minutes and try loading the page again?

**Comment by shuchibooksmith** [comment] 2016-03-07 15:30
sure thing, will do.
but to clarify (so we're on the same page) the issue i'm seeing is that 
the caption for the post is coming up first, underneath the banner, then 
the list of all the kidsmith blog posts, then the comic strip, then the 
caption again.

On 3/7/2016 10:26 AM, Bud Parr wrote:
>
> I took off some "value added" stuff the DISQUS commenting system was 
> adding to the page. My only guess at this point is that the 
> third-party script for the comments was blocking the loading of the 
> page. At any rate, that's what it looks like, and could be why it's 
> not happening on my test devices. Can you wait 5 minutes and try 
> loading the page again?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/141#issuecomment-193297701>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

P Please consider the environment before printing this email.

**Comment by budparr** [comment] 2016-03-07 15:36
Funny. All along I thought issue was with the address bar on your browser. The caption part is because someone put that in incorrectly (that's for a banner image). The list of kidsmith posts is a good call. I put that sort of "aside" information on the top of pages because it's usually relevant to the content below. Here (on posts) I should move them so they flow below the content. No problem on that.

**Comment by zchyde** [comment] 2016-03-07 15:56
Wait what happened? I'm the one who made that post so what did I do wrong?

**Comment by budparr** [comment] 2016-03-07 15:58
No big deal. There was a caption for the banner image that was a duplicate of the copy below the image.

**Comment by budparr** [comment] 2016-03-07 15:58
I removed it.

**Comment by zchyde** [comment] 2016-03-07 16:06
huh ok. Maybe that wasn't me, I dont remember putting a caption. Well anyway cool, thanks guys.

**Closed** 2016-03-07 16:17 UTC
Labels: bug

**Comment by budparr** [comment] 2016-03-07 16:19
I moved the post list (of other posts in that category) to the right, so that on mobile they flow below the content (which is appropriate).
